name: flutter_learning
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev


environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  ##full Scren yapmaya yarıyor
  full_screen_image_null_safe: ^2.0.0
  ##Api için post get vb methodlarını yazmaya yarar.
  dio: ^4.0.6
  ##Animation için
  flutter_spinkit: ^5.1.0
  ##Animation tarzı görseller
  lottie: ^1.4.3
  ##url
  url_launcher: ^6.1.5
  image_picker: ^0.8.5+3
  json_serializable: ^6.4.0
  ##for cache
  shared_preferences: ^2.0.15
  json_annotation: ^4.5.0
  ##Context
  kartal: ^2.4.3
  ##secure context
  flutter_secure_storage: ^6.0.0
  ##states
  provider: ^6.0.3
  flutter_mobx: ^2.0.6+4
  mobx: ^2.1.0
  mobx_codegen: ^2.0.7+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  ##test
  mockito: ^5.3.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/png/apple-and-book-png-apple-on-books-svg-scrapbook-cut-file-cute-clipart-files-for-silhouette-cricut-pazzles-free-svgs-free-svg-cuts-cute-cut-files-432.png
    - assets/png/stats.png
    - assets/png/restaurant.png
    - assets/png/Interior-Design-Elements-Northern-Kentucky-Cincinnati.jpg
    - assets/png/living-10-1.jpg
    - assets/png/roomdesign.jpg
    - assets/png/diningtable.jpg
    - assets/png/bedroom.jpg
    - assets/png/coffetable.jpg
    - assets/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
